#!/usr/bin/env ruby
kernel_val = ENV['KERNEL'] || "null"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/#{ENV['BOX_NAME']}"
  config.vm.provision "shell", 
                        path: "provision1.sh", 
                        args: "#{ENV['BOX_NAME']} #{kernel_val}"

  if ENV['KERNEL'] == 'mainline'
    config.vm.provision :reload
  end

  config.vm.provision "shell", 
                        path: "provision2.sh", 
                        args: "#{ENV['BOX_NAME']} #{ENV['SYSTEM_PULLREQUEST_PULLREQUESTNUMBER']}"

  config.vm.define "#{ENV['BOX_NAME']}" do |vm01|
    vm01.vm.provider :libvirt do |libvirt|
      vm01.vm.box_check_update = false
      libvirt.memory = 8192
      libvirt.cpus = 8
    end
  end
end
